version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: robot_monitor
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    image: robot-backend:latest  # 로컬 이미지
    ports:
      - "8288:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/robot_monitor?useSSL=false&serverTimezone=Asia/Seoul
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: 1234
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    image: robot-frontend:latest  # 로컬 이미지
    ports:
      - "8233:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: